Import([ "env" ])

# platform is responsible for linking graphics libraries, rather than graphics
# graphics libraries differ by platform, e.g. GL vs. OpenGL32

modules = []
for module in [ "platform", "graphics" ]:
	modules.extend(env.SConscript(
		module + "/SConscript",
		exports = [ "env" ], duplicate = False
	))

machinist = env.Program("machinist", Glob("*.cpp") + modules)

Return([ "machinist" ])
