import machinist
Import([ "env" ])

objects = machinist.Objects(env, Glob("*.cpp"))
env.Append(LIBS = [ "opengl32", "gdi32" ], LINKFLAGS = [ "-static-libgcc", "-static-libstdc++" ])

Return([ "objects" ])
