Import([ "env" ])

objects = env.SConscript(
	"$graphics/SConscript", exports = [ "env" ],
	variant_dir = "api", duplicate = False
) + [ env.Object(source) for source in Glob("*.cpp") ]

env.Append(LIBS = [ "IL" ])

Return([ "objects" ])
